<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Файлы модели теперь находятся внутри проекта в папке Models, SDK подключит их автоматически -->

  <ItemGroup>
    <Compile Include="..\Models\Courier.cs" />
    <Compile Include="..\Models\Parcel.cs" />
    <Compile Include="..\ParcelStatus.cs" />
  </ItemGroup>

</Project>
